server:
  port: 6001

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大空闲连接数
        max-idle: 8
        # 最大等待时长
        max-wait: 100
